// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/consumption": {
            "get": {
                "description": "Retorna el consumo acumulado por periodo para los medidores dados",
                "tags": [
                    "consumption"
                ],
                "summary": "Obtener consumos",
                "parameters": [
                    {
                        "type": "string",
                        "description": "IDs de medidores separados por coma",
                        "name": "meters_ids",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Fecha inicio (YYYY-MM-DD)",
                        "name": "start_date",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Fecha fin (YYYY-MM-DD)",
                        "name": "end_date",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tipo de periodo: daily, weekly, monthly",
                        "name": "kind_period",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.ConsumptionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.ConsumptionResponse": {
            "type": "object",
            "properties": {
                "data_graph": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.MeterData"
                    }
                },
                "period": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "domain.MeterData": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "address": {
                    "type": "string"
                },
                "exported": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "meter_id": {
                    "type": "integer"
                },
                "reactive_capacitive": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "reactive_inductive": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "BIA Microservicio de Consumos",
	Description:      "API para consultar consumos de energía por medidor",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
